---
- name: Remove existing container
  docker_container:
    name: portainer
    state: absent
    networks: []
    comparisons:
      networks: strict
    force_kill: true
  when: remove_existing_container

- name: Remove persistent data
  file:
    state: absent
    path: "{{ persistent_data_path.split(\":\") | first | string }}"
  when: remove_persistent_data
