---
- debug:
    msg: "{{ lookup('template', 'settings.json.j2') | from_json | to_json }}"
    verbosity: 1

- name: Configure Portainer settings
  uri:
    url: "{{ portainer_endpoint }}/settings"
    method: PUT
    return_content: true
    headers:
      Authorization: "Bearer {{ (auth_token.content|from_json).jwt }}"
    body_format: json
    body: "{{ lookup('template','settings.json.j2') | from_json | to_json }}"


